<?php

namespace App\Controllers;

use App\Core\Attributes\Route;
use App\Core\Controller;
use App\Core\Response;


class NewsController extends Controller
{
    #[Route("lists")]
    public function list(): Response
    {


        return new Response('List', 'List!!');
    }

    #[Route("addition")]
    public function add(): Response
    {

        return new Response('Add', 'Add!!');
    }

    #[Route("home")]
    public function index(): ?string
    {
        return $this->render([
            'title' => 'text1',
            'text' => 'some text1',
            'date' => '2023-08-14']);
       // return new Response('Index', 'Index!!');
    }

//    public function render(array $assoc_array):string{
//        $assoc_array['module']='news';
//    }
    public function render(array $assoc_array): string
    {
        $assoc_array['module'] = 'news';
        return parent::render($assoc_array); // TODO: Change the autogenerated stub
    }
}